		page 60,132
TITLE	EXJUMP COM
CODESG	SEGMENT PARA 'Code'
		ASSUME	CS:CODESG,DS:CODESG,SS:CODESG
		ORG		100H

MAIN	PROC	NEAR
		MOV		AX,01
		MOV		BX,01
		MOV		CX,01
A20:	
		ADD		AX,01
		ADD		BX,AX
		SHL		CX,1
		JMP		A20
MAIN	ENDP
CODESG	ENDS
		END		MAIN