		PAGE	60,132
		TITLE EX65(COM) Homework 6.5
;---------------------------------------------------
SCODE	SEGMENT	PARA 'Code'
		ASSUME	SS:SCODE,CS:SCODE,DS:SCODE,ES:SCODE
		ORG		100H
BEGIN:	JMP		MAIN
		FLDA	DB		28H
		FLDB	DB		14H
		FLDC	DW		?
MAIN	PROC	NEAR
		MOV		AL,FLDA
		SHL		AL,1
		MOV		BL,FLDB
		MUL		BL
		MOV		FLDC,AX
		RET
MAIN	ENDP
SCODE	ENDS
		END		BEGIN